return {
  -- competitive programming
  -- inspired by https://github.com/ncduy0303/Competitive-Programming/blob/master/Contest%20Template/main.cpp
  s('cp', {
    t {
      '#include <bits/stdc++.h>',
      '',
      'using namespace std;',
      '',
      "template<typename A, typename B> ostream& operator<<(ostream &os, const pair<A, B> &p) { return os << '(' << p.first << \", \" << p.second << ')'; }",
      "template<typename T_container, typename T = typename enable_if<!is_same<T_container, string>::value, typename T_container::value_type>::type> ostream& operator<<(ostream &os, const T_container &v) { os << '{'; string sep; for (const T &x : v) os << sep << x, sep = \", \"; return os << '}'; }",
      'void dbg_out() { cerr << endl << flush; }',
      "template<typename Head, typename... Tail> void dbg_out(Head H, Tail... T) { cerr << ' ' << H; dbg_out(T...); }",
      '#ifdef LOCAL',
      '#define dbg(...) cerr << "(" << #__VA_ARGS__ << "):", dbg_out(__VA_ARGS__)',
      '#else',
      '#define dbg(...)',
      '#endif',
      '',
      '#define ar array',
      '#define ll long long',
      '#define ld long double',
      '#define sza(x) ((int)x.size())',
      '#define all(a) (a).begin(), (a).end()',
      '',
      'const int MAX_N = 1e5 + 5;',
      'const ll MOD = 1e9 + 7;',
      'const ll INF = 1e9;',
      'const ld EPS = 1e-9;',
      '',
      'template<typename T>',
      'void read_vector(vector<T>& v) {',
      '    for (int i=0;i<v.size();++i)cin>>v[i];',
      '}',
      '// declare and read vector for given type and size',
      '#define drvec(t, n, v) vector<t> v(n);read_vector(v);',
      '',
      'void solve() {',
      '    ',
      '}',
      '',
      'int main() {',
      '    ios_base::sync_with_stdio(0);',
      '    cin.tie(0); cout.tie(0);',
      '    int tc = 1;',
      '    // cin >> tc;',
      '    for (int t = 1; t <= tc; t++) {',
      '        // cout << "Case #" << t << ": ";',
      '        solve();',
      '    }',
      '}',
    },
  }),
  s('fenwick', {
    t {
      'class FenwickTree{',
      '    vector<ll> arr;',
      'public:',
      '    FenwickTree(int n): arr(n+1){',
      '    }',
      '',
      '    void add(int idx, int val) {',
      '        while (idx<arr.size()) {',
      '            arr[idx]+=val;',
      '            idx+=idx&(-idx);',
      '        }',
      '    }',
      '    ll sum(int idx) {',
      '        if (idx<=0) return 0;',
      '        if (idx >= arr.size()) idx = arr.size() - 1;  // Handle boundary',
      '        ll ans=0;',
      '        while (idx>0) {',
      '            ans+=arr[idx];',
      '            idx-=idx&(-idx);',
      '        }',
      '        return ans;',
      '    }',
      '    // assumption: the tree add 1 at position x',
      '    // for each x in original array',
      "    // so origal array each element less than this tree's size",
      '    // find minimum idx that sum(idx) >= ith (base 1)',
      '    // return arr.size() if not found',
      '    int find_ith(int ith) {',
      '        ll lo=1, hi=arr.size();',
      '        assert(ith>0);',
      '        while (lo < hi) {',
      '            ll m = lo+(hi-lo)/2;',
      '            // dbg(lo,hi,m);',
      '            if (sum(m)<ith) lo=m+1;',
      '            else hi=m;',
      '        }',
      '        return lo;',
      '    }',
      '',
      '};',
    },
  }),
}
